### PR TITLE
Switch to Boost.Core's lightweight_test

### PR DESCRIPTION
**Pull request by glenfe**
The dependencies for testing decrease significantly (as shown in the `cmake/dependencies.cmake` diff) as does the time to build and run the tests.

### CODE REVIEW

**Comment by glenfe** [comment]
@tzlaine Looks like on OSX the tests are using the system installed Boost which doesn't have newer facilities in <boost/core/lightweight_test.hpp>, while on Linux they're cloning Boost from Github. Any objection to making the OSX tests do the same?

**Comment by tzlaine** [comment]
No objection.  I probably should have been doing that all along.

Zach

**Comment by glenfe** [comment]
@tzlaine Done.

**Comment by tzlaine** [comment]
Thanks, Glen!

Zach

**Pull request merged**
