### PR TITLE
Add a Boost-friendly subproject case to CMakeLists

### PR DESCRIPTION
**Pull request by pdimov**

### CODE REVIEW

**Comment by pdimov** [comment]
It should be possible to update `cmake/dependencies.cmake` to use `FetchContent` for only the required Boost dependencies nowadays, if you like this sort of thing. :-)

**Comment by tzlaine** [comment]
Thanks, Peter.  Where can I find FetchContent?  I assume that's a thing you've created?

**Comment by pdimov** [comment]
`FetchContent` is a standard CMake module in 3.9 and up: https://cmake.org/cmake/help/latest/module/FetchContent.html

**Comment by tzlaine** [comment]
Thanks!  I had no idea.

**Pull request merged**
